// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace KoiFarmShop.Data.Models;

[Table("Care_Request_Detail")]
public partial class CareRequestDetail
{
    [Key]
    [Column("care_request_detail_id")]
    public int CareRequestDetailId { get; set; }

    [Column("care_request_id")]
    public int? CareRequestId { get; set; }

    [Column("koi_image")]
    public string KoiImage { get; set; }

    [Column("service_description")]
    public string ServiceDescription { get; set; }

    [Column("status", TypeName = "varchar(50)")]
    [StringLength(50)]
    public string Status { get; set; }

    [Column("note")]
    public string Note { get; set; }

    [Column("created_by")]
    [StringLength(255)]
    public string CreatedBy { get; set; }

    [Column("updated_by")]
    [StringLength(255)]
    public string UpdatedBy { get; set; }

    [ForeignKey("CareRequestId")]
    [InverseProperty("CareRequestDetails")]
    public virtual CareRequest CareRequest { get; set; }
    public enum CareRequestDetailStatus
    {
        [Display(Name = "In Progress")]
        InProgress,
        Completed
    }
}