// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace KoiFarmShop.Data.Models;

[Table("Care_Plan")]
public partial class CarePlan
{
    [Key]
    [Column("care_plan_id")]
    public int CarePlanId { get; set; }

    [Column("name")]
    [StringLength(255)]
    public string Name { get; set; }

    [Column("description")]
    public string Description { get; set; }

    [Column("duration_days")]
    public int? DurationDays { get; set; }

    [Column("price", TypeName = "decimal(10, 2)")]
    public decimal? Price { get; set; }

    [Column("is_active")]
    public bool? IsActive { get; set; }

    [InverseProperty("CarePlan")]
    public virtual ICollection<CareRequest> CareRequests { get; set; } = new List<CareRequest>();
}