// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace KoiFarmShop.Data.Models;

[Table("Care_Request")]
public partial class CareRequest
{
    [Key]
    [Column("care_request_id")]
    public int CareRequestId { get; set; }

    [Column("customer_id")]
    public int? CustomerId { get; set; }

    [Column("koi_id")]
    public int? KoiId { get; set; }

    [Column("care_plan_id")]
    public int? CarePlanId { get; set; }

    [Column("start_date", TypeName = "datetime")]
    public DateTime? StartDate { get; set; }

    [Column("status")]
    [StringLength(50)]
    public CareRequestStatus Status { get; set; }

    [Column("total_amount", TypeName = "decimal(10, 2)")]
    public decimal? TotalAmount { get; set; }

    [Column("created_by")]
    [StringLength(255)]
    public string CreatedBy { get; set; }

    [Column("updated_by")]
    [StringLength(255)]
    public string UpdatedBy { get; set; }

    [ForeignKey("CarePlanId")]
    [InverseProperty("CareRequests")]
    public virtual CarePlan CarePlan { get; set; }

    [InverseProperty("CareRequest")]
    public virtual ICollection<CareRequestDetail> CareRequestDetails { get; set; } = new List<CareRequestDetail>();

    public enum CareRequestStatus
    {
        PendingApproval,
        Active,
        Completed,
        Rejected
    }
}