// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiFarmShop.Data.Models;

public partial class Certification
{
    public int CertificateId { get; set; }

    public int OrderItemId { get; set; }

    public string Origin { get; set; }

    public string Image { get; set; }

    public string HealthStatusDescription { get; set; }

    public string Award { get; set; }

    public virtual OrderItem OrderItem { get; set; }
}