// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiFarmShop.Data.Models;

public partial class ConsignmentRequest
{
    public int ConsignmentId { get; set; }

    public int CustomerId { get; set; }

    public double? SubAmount { get; set; }

    public double? Vat { get; set; }

    public double? VatAmount { get; set; }

    public double? PromotionAmount { get; set; }

    public double? TotalAmount { get; set; }

    public double? PaymentMethod { get; set; }

    public string PaymentStatus { get; set; }

    public bool? IsActive { get; set; }

    public string Note { get; set; }

    public string Status { get; set; }

    public bool? IsOnline { get; set; }

    public virtual ICollection<ConsignmentDetail> ConsignmentDetails { get; set; } = new List<ConsignmentDetail>();

    public virtual Customer Customer { get; set; }
}