// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace KoiFarmShop.Data.Models;

[Table("Consignment_Request")]
[Index("KoiId", Name = "UQ_ConsignmentRequest_Koi", IsUnique = true)]
public partial class ConsignmentRequest
{
    [Key]
    [Column("consignment_id")]
    public int ConsignmentId { get; set; }

    [Column("customer_id")]
    public int? CustomerId { get; set; }

    [Column("koi_id")]
    public int? KoiId { get; set; }

    [Column("argred_sale_price", TypeName = "decimal(10, 2)")]
    public decimal? ArgredSalePrice { get; set; }

    [Column("start_date", TypeName = "datetime")]
    public DateTime? StartDate { get; set; }

    [Column("end_date", TypeName = "datetime")]
    public DateTime? EndDate { get; set; }

    [Column("is_active")]
    public bool? IsActive { get; set; }

    [Column("status", TypeName = "varchar(55)")]
    [StringLength(50)]
    public ConsignmentStatus Status { get; set; }

    [Column("note")]
    public string Note { get; set; }

    [Column("created_at", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column("updated_at", TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    [Column("updated_by")]
    [StringLength(255)]
    public string UpdatedBy { get; set; }

    [InverseProperty("Consignment")]
    public virtual ConsignmentTransaction ConsignmentTransaction { get; set; }

    [ForeignKey("CustomerId")]
    [InverseProperty("ConsignmentRequests")]
    public virtual Customer Customer { get; set; }

    [ForeignKey("KoiId")]
    [InverseProperty("ConsignmentRequest")]
    public virtual Koi Koi { get; set; }

    public enum ConsignmentStatus
    {
        pending, rejected, approved, complete
    }
}