// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace KoiFarmShop.Data.Models;

[Table("Consignment_Transaction")]
public partial class ConsignmentTransaction
{
    [Key]
    [Column("transaction_id")]
    public int TransactionId { get; set; }

    [Column("consignment_id")]
    public int? ConsignmentId { get; set; }

    [Column("sale_price", TypeName = "decimal(10, 2)")]
    public decimal? SalePrice { get; set; }

    [Column("commission_fee", TypeName = "decimal(10, 2)")]
    public decimal? CommissionFee { get; set; }

    [Column("commission_amount", TypeName = "numeric(13, 4)")]
    public decimal? CommissionAmount { get; set; }

    [Column("earnings", TypeName = "decimal(11, 2)")]
    public decimal? Earnings { get; set; }

    [Column("sold_at", TypeName = "datetime")]
    public DateTime? SoldAt { get; set; }

    [ForeignKey("ConsignmentId")]
    [InverseProperty("ConsignmentTransactions")]
    public virtual ConsignmentRequest Consignment { get; set; }
}