// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiFarmShop.Data.Models;

public partial class ConsignmentDetail
{
    public int ConsignmentDetailId { get; set; }

    public int ConsignmentId { get; set; }

    public int KoiId { get; set; }

    public string ConsignmentType { get; set; }

    public double? MonthlyConsignmentFee { get; set; }

    public double? SoldPrice { get; set; }

    public string HealthDescription { get; set; }

    public double? Weight { get; set; }

    public string Status { get; set; }

    public bool? IsActive { get; set; }

    public string Note { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string UpdatedBy { get; set; }

    public virtual ConsignmentRequest Consignment { get; set; }

    public virtual Koi Koi { get; set; }
}