// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiFarmShop.Data.Models;

public partial class Feedback
{
    public int FeedbackId { get; set; }

    public int OrderId { get; set; }

    public int? CustomerId { get; set; }

    public string Content { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual Order Order { get; set; }
}