// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace KoiFarmShop.Data.Models;

public partial class KoiType
{
    [Key]
    public int KoiTypeId { get; set; }

    public string Name { get; set; }

    public string ShortDescription { get; set; }

    public string OriginHistory { get; set; }

    public string CategoryDescription { get; set; }

    public string FengShui { get; set; }

    public string RaisingCondition { get; set; }

    public string Note { get; set; }

    [DataType(DataType.Date)]
    public DateTime? CreatedAt { get; set; } = DateTime.UtcNow;

    public string CreatedBy { get; set; }

    [DataType(DataType.Date)]
    public DateTime? UpdatedAt { get; set; }

    public string UpdatedBy { get; set; }

    public virtual ICollection<Koi> Kois { get; set; } = new List<Koi>();
}