// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace KoiFarmShop.Data.Models;

[Table("Token")]
public partial class Token
{
    [Key]
    [Column("user_id")]
    public int UserId { get; set; }

    [Required]
    public string AccessToken { get; set; }

    [Required]
    public string RefreshToken { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ExpiredTime { get; set; }

    public int Status { get; set; }
}